#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-pycurl
Version  : 7.43.0.2
Release  : 59
URL      : https://dl.bintray.com/pycurl/pycurl/pycurl-7.43.0.2.tar.gz
Source0  : https://dl.bintray.com/pycurl/pycurl/pycurl-7.43.0.2.tar.gz
Summary  : PycURL -- A Python Interface To The cURL library
Group    : Development/Tools
License  : ICU LGPL-2.1
Requires: deprecated-pycurl-license = %{version}-%{release}
Requires: deprecated-pycurl-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : curl
BuildRequires : curl-dev
BuildRequires : nghttp2-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(libidn)
BuildRequires : python-dev
BuildRequires : zlib-dev

%description
PycURL -- A Python Interface To The cURL library
================================================

%package doc
Summary: doc components for the deprecated-pycurl package.
Group: Documentation

%description doc
doc components for the deprecated-pycurl package.


%package legacypython
Summary: legacypython components for the deprecated-pycurl package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-pycurl package.


%package license
Summary: license components for the deprecated-pycurl package.
Group: Default

%description license
license components for the deprecated-pycurl package.


%package python
Summary: python components for the deprecated-pycurl package.
Group: Default

%description python
python components for the deprecated-pycurl package.


%prep
%setup -q -n pycurl-7.43.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554343939
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2 --with-ssl

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-pycurl
cp COPYING-LGPL %{buildroot}/usr/share/package-licenses/deprecated-pycurl/COPYING-LGPL
cp COPYING-MIT %{buildroot}/usr/share/package-licenses/deprecated-pycurl/COPYING-MIT
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files doc
%defattr(0644,root,root,0755)
%exclude /usr/share/doc/pycurl/AUTHORS
%exclude /usr/share/doc/pycurl/COPYING-LGPL
%exclude /usr/share/doc/pycurl/COPYING-MIT
%exclude /usr/share/doc/pycurl/ChangeLog
%exclude /usr/share/doc/pycurl/INSTALL.rst
%exclude /usr/share/doc/pycurl/README.rst
%exclude /usr/share/doc/pycurl/RELEASE-NOTES.rst
%exclude /usr/share/doc/pycurl/examples/basicfirst.py
%exclude /usr/share/doc/pycurl/examples/file_upload.py
%exclude /usr/share/doc/pycurl/examples/linksys.py
%exclude /usr/share/doc/pycurl/examples/opensocketexception.py
%exclude /usr/share/doc/pycurl/examples/quickstart/file_upload_buffer.py
%exclude /usr/share/doc/pycurl/examples/quickstart/file_upload_real.py
%exclude /usr/share/doc/pycurl/examples/quickstart/file_upload_real_fancy.py
%exclude /usr/share/doc/pycurl/examples/quickstart/follow_redirect.py
%exclude /usr/share/doc/pycurl/examples/quickstart/form_post.py
%exclude /usr/share/doc/pycurl/examples/quickstart/get.py
%exclude /usr/share/doc/pycurl/examples/quickstart/get_python2.py
%exclude /usr/share/doc/pycurl/examples/quickstart/get_python2_https.py
%exclude /usr/share/doc/pycurl/examples/quickstart/get_python3.py
%exclude /usr/share/doc/pycurl/examples/quickstart/get_python3_https.py
%exclude /usr/share/doc/pycurl/examples/quickstart/put_buffer.py
%exclude /usr/share/doc/pycurl/examples/quickstart/put_file.py
%exclude /usr/share/doc/pycurl/examples/quickstart/response_headers.py
%exclude /usr/share/doc/pycurl/examples/quickstart/response_info.py
%exclude /usr/share/doc/pycurl/examples/quickstart/write_file.py
%exclude /usr/share/doc/pycurl/examples/retriever-multi.py
%exclude /usr/share/doc/pycurl/examples/retriever.py
%exclude /usr/share/doc/pycurl/examples/sfquery.py
%exclude /usr/share/doc/pycurl/examples/smtp.py
%exclude /usr/share/doc/pycurl/examples/ssh_keyfunction.py
%exclude /usr/share/doc/pycurl/examples/xmlrpc_curl.py

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-pycurl/COPYING-LGPL
/usr/share/package-licenses/deprecated-pycurl/COPYING-MIT

%files python
%defattr(-,root,root,-)
